apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: car
  name: car-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: car
  type: LoadBalancer
status:
  loadBalancer: {}
